### ISSUE TITLE
Create video from multiples images ?

### ISSUE THREAD

**Issue by olivbrau** [a-schild/jave2#121] opened 2020-10-05 13:30 UTC
Hi.
Is it possible to create a video from a list of images ? 
Ideally, the images are in memory, generated by the Java program, and integrated in the video one after the other.
Or possibly, they are first stored on the hard drive, and then converted to a video.
Thanks a lot for your help !
Olivier

**Comment by mressler** [comment] 2020-10-05 18:26
Duplicate of #108.

**Closed by mressler** 2020-10-05 18:26 UTC
