### ISSUE TITLE
There is a problem getting the video width and height(获取视频宽高有问题)

### ISSUE THREAD

**Issue by SophieRoyal** [a-schild/jave2#87] opened 2020-06-19 03:39 UTC
There is a problem in getting the width and height of the video. I used douyin and other similar websites to download the video. When I got the information, I found that the width and height of the video were the same.
       获取视频宽高有问题，我采用抖音等类似网站下载的视频，在获取信息时，发现视频宽高是相等的，但是打开明显不是？

**Comment by a-schild** [comment] 2020-06-19 12:03
Please provide an reproducable example of what is not working

**Comment by SophieRoyal** [comment] 2020-06-20 00:39
@a-schild for-example : http://106.52.134.22:9080/bladex/library/pic_2fb7a1b8016c6d5db63f36f82ba56ada_1206409.mp4
I uploaded the file for width **640*640**，But the reality is that **360 * 640**
http://106.52.134.22:9080/bladex/library/pic_3b822100ef10c3999510e66a6800ac29_1720207.mp4
I uploaded the file for width **960*960**，But the reality is that **544 * 960**

**Comment by a-schild** [comment] 2020-06-24 10:22
Please show your code which you did use for conversion

**Comment by SophieRoyal** [comment] 2020-06-27 08:48
`/**
	 * 获取媒体文件分辨率
	 * @param file:文件地址
	 * @return
	 * @throws EncoderException
	 */
	public static String getResolution(File file) throws EncoderException {
		MultimediaInfo info = getMediaInfo(file);
		int height = info.getVideo().getSize().getHeight();
		int width = info.getVideo().getSize().getHeight();
		return width + "*" + height;
	}` 
@a-schild

**Comment by a-schild** [comment] 2020-06-29 07:36
I did test it, but the video sizes are detected correctly.

```
    public void testGetInfo06() throws Exception {
        System.out.println("testGetInfo06");
        File file = new File(getResourceSourcePath(), "size1.mp4");
        MultimediaObject instance = new MultimediaObject(file);
        MultimediaInfo result = instance.getInfo();
        assertEquals("mov", result.getFormat(),  "Invalid video format");
        assertEquals(640, result.getVideo().getSize().getHeight(), "Video height not as expected");
        assertEquals(360, result.getVideo().getSize().getWidth(), "Video width not as expected");
    }

    /**
     * Test of getInfo method, of class MultimediaObject.
     * @throws java.lang.Exception
     */
    @Test
    public void testGetInfo07() throws Exception {
        System.out.println("testGetInfo07");
        File file = new File(getResourceSourcePath(), "size2.mp4");
        MultimediaObject instance = new MultimediaObject(file);
        MultimediaInfo result = instance.getInfo();
        assertEquals("mov", result.getFormat(),  "Invalid video format");
        assertEquals(960, result.getVideo().getSize().getHeight(), "Video height not as expected");
        assertEquals(544, result.getVideo().getSize().getWidth(), "Video width not as expected");
    }
```

**Comment by SophieRoyal** [comment] 2020-06-29 08:42
Identify the problem.
I uploaded it through MultipartFile, used binary to File, and then got the resolution through File.
Just now I tested your code and it was correct, but there seems to be a problem after I converted it.
`public R<FileObj> putFile(MultipartFile file) {
		String resolution = "";
		// time
		long duration = 0L;
		File _file = new File(file.getOriginalFilename());
		FileUtils.copyInputStreamToFile(file.getInputStream(), _file);
			System.out.println("start read");
			duration = VideoUtil.getTime(_file);
			System.out.println("get resolution");
			resolution = VideoUtil.getResolution(_file);;
		`
`public static long getTime(File file) throws EncoderException {
		MultimediaInfo info = getMediaInfo(file);
		long time = info.getDuration();
		return info.getDuration();
	}
	public static String getResolution(File file) throws EncoderException {
		MultimediaInfo info = getMediaInfo(file);
		int height = info.getVideo().getSize().getHeight();
		int width = info.getVideo().getSize().getHeight();
		return width + "*" + height;
	}`

**Comment by a-schild** [comment] 2020-06-29 08:56
So what's the problem now?

**Comment by mressler** [comment] 2020-07-20 03:38
Looks like this should be marked as closed. @a-schild

**Closed** 2020-07-22 06:44 UTC
Labels: invalid
