### ISSUE TITLE
get video Info erro

### ISSUE THREAD

**Issue by tomato-cc** [a-schild/jave2#80] opened 2020-04-14 04:21 UTC
MultimediaObject multimediaObject = new MultimediaObject(source);
            // 获得原视频参数信息
            MultimediaInfo info = multimediaObject.getInfo();

            // 设置值编码
            Encoder ec = new Encoder();
            ec.encode(multimediaObject, target, attr);

erro msg:
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
ws.schild.jave.EncoderException: Exit code of ffmpeg encoding run is 1
	at ws.schild.jave.Encoder.encode(Encoder.java:691)
	at ws.schild.jave.Encoder.encode(Encoder.java:398)
	at ws.schild.jave.Encoder.encode(Encoder.java:363)
	at tomatocc.java2.videoZIp.compre(videoZIp.java:69)
	at tomatocc.java2.videoZIp.main(videoZIp.java:19)

**Comment by a-schild** [comment] 2020-04-14 06:37
What is the `source` file with video file?
Looks like it has problems analyzing it

**Comment by tomato-cc** [comment] 2020-04-14 07:22
public static void main(String[] args) throws EncoderException {
        // 压缩前文件路径
        File source = new File("D:/video/000.mp4");
        // 压缩后的文件路径
        File target = new File("D:/video/comp111.mp4");
        compre(source,target,1);
    }

    /**
     * 视频压缩
     * @param source 源文件
     * @param target 目标文件
     * @param rate 压缩比
     */
    public static void compre(File source, File target, Integer rate){
        try {
            System.out.println("begin");
            long start = System.currentTimeMillis();
            // 获得原视频参数信息
            MultimediaObject multimediaObject = new MultimediaObject(source);
         // 获得原视频参数信息
        MultimediaInfo info = multimediaObject.getInfo();;

        // 获取源文件音频流
           AudioInfo sourceAudio = info.getAudio();
            // 获取源文件视频流
            VideoInfo sourceVideo = info.getVideo();

            // 音频编码属性配置
            AudioAttributes audio= new AudioAttributes();
            audio.setCodec("libmp3lame");
            // 设置音频比特率,单位:b (比特率越高，清晰度/音质越好，当然文件也就越大 56000 = 56kb)
            audio.setBitRate(new Integer(56_000));
            // 设置重新编码的音频流中使用的声道数（1 =单声道，2 = 双声道（立体声））
            audio.setChannels(sourceAudio.getChannels());
            // 采样率越高声音的还原度越好，文件越大
            audio.setSamplingRate(sourceAudio.getSamplingRate());

            // 视频编码属性配置
            VideoAttributes video=new VideoAttributes();
            // 设置编码
            video.setCodec("mpeg4");
            //设置音频比特率,单位:b (比特率越高，清晰度/音质越好，当然文件也就越大 5600000 = 5600kb)
            video.setBitRate(new Integer(5_600_000 / rate));
            // 设置视频帧率（帧率越低，视频会出现断层，越高让人感觉越连续）,这里 除1000是为了单位转换
            video.setFrameRate(new Integer(Math.round(sourceVideo.getFrameRate() / 1_000)));


            // 编码设置
            EncodingAttributes attr=new EncodingAttributes();
            attr.setFormat("mp4");
            attr.setAudioAttributes(audio);
            attr.setVideoAttributes(video);

            // 设置值编码
            Encoder ec = new Encoder();
            ec.encode(multimediaObject, target, attr);


            System.out.println("end");
            long end = System.currentTimeMillis();

            System.out.println("压缩前大小： "+source.length() + " 压缩后大小：" + target.length());

            System.out.println("压缩耗时： " + (end -start));

        } catch (EncoderException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        }

    }

**Comment by tomato-cc** [comment] 2020-04-14 07:24
I want to get the parameters of the source video, but there is an error

**Comment by a-schild** [comment] 2020-04-22 07:26
There must be a problem with the source file.
Can you post (an extract) of the video here?

**Comment by tomato-cc** [comment] 2020-04-22 11:46
I send email to your email addr andre@schild.ws

**Comment by mressler** [comment] 2020-08-16 16:23
@a-schild Can we update this with the link or close the issue?

**Comment by a-schild** [comment] 2020-08-17 06:56
No able to reproduce

**Closed by a-schild** 2020-08-17 06:56 UTC
